name: Use Github App
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  checkout-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ vars.GH_APPLICATION_ID }}
          application_private_key: ${{ secrets.GH_APPLICATION_KEY }}

      - uses: actions/checkout@v3
        with:
            token: ${{ steps.get_workflow_token.outputs.token }}
            repository: vodkaslime/test-repo

      - run: git clone "https://user:${{ steps.get_workflow_token.outputs.token }}github.com/vodkaslime/test-repo.git"