name: python lints

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v1
        - uses: ricardochaves/python-lint@master
          with:
            python-root-list: "src"